
package soapapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PostAPI", targetNamespace = "http://webapi.kwetter/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostAPI {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webapi.kwetter/PostAPI/postNewTweetRequest", output = "http://webapi.kwetter/PostAPI/postNewTweetResponse")
    public String postNewTweet(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns soapapi.TimeLine
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webapi.kwetter/PostAPI/getUsertimelineRequest", output = "http://webapi.kwetter/PostAPI/getUsertimelineResponse")
    public TimeLine getUsertimeline(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
