
package soapapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PostAPIService", targetNamespace = "http://webapi.kwetter/", wsdlLocation = "http://nieks-mbp:8080/kwetter/PostAPIService?wsdl")
public class PostAPIService
    extends Service
{

    private final static URL POSTAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException POSTAPISERVICE_EXCEPTION;
    private final static QName POSTAPISERVICE_QNAME = new QName("http://webapi.kwetter/", "PostAPIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://nieks-mbp:8080/kwetter/PostAPIService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSTAPISERVICE_WSDL_LOCATION = url;
        POSTAPISERVICE_EXCEPTION = e;
    }

    public PostAPIService() {
        super(__getWsdlLocation(), POSTAPISERVICE_QNAME);
    }

    public PostAPIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTAPISERVICE_QNAME, features);
    }

    public PostAPIService(URL wsdlLocation) {
        super(wsdlLocation, POSTAPISERVICE_QNAME);
    }

    public PostAPIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTAPISERVICE_QNAME, features);
    }

    public PostAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostAPI
     */
    @WebEndpoint(name = "PostAPIPort")
    public PostAPI getPostAPIPort() {
        return super.getPort(new QName("http://webapi.kwetter/", "PostAPIPort"), PostAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostAPI
     */
    @WebEndpoint(name = "PostAPIPort")
    public PostAPI getPostAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webapi.kwetter/", "PostAPIPort"), PostAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTAPISERVICE_EXCEPTION!= null) {
            throw POSTAPISERVICE_EXCEPTION;
        }
        return POSTAPISERVICE_WSDL_LOCATION;
    }

}
